### ISSUE TITLE
Where does powerpc-eabi-gcc linker come from?

### ISSUE THREAD

**Issue by ghost** [rust-wii/testing-project#3]
I have both `devkitppc` installed as well as some random toolchain I found on the AUR. Is this only for Windows?

**Comment by FrictionlessPortals** [comment]
The ``powerpc-eabi-gcc`` linker should be located under ``/opt/devkitpro/devkitPPC/bin/``. This folder should be part of your path setup by devkitPro when the ``devkitppc`` package is installed.
