### ISSUE TITLE
Would this compile with any other crate?

### ISSUE THREAD

**Issue by TheTechRobo** [rust-wii/testing-project#4]
For example, if I were to make a game with bevy, would I just add it to the Cargo.toml and use it or are there extra steps? Would the Wii be ok with it?

**Comment by FrictionlessPortals** [comment]
Currently the Wii is most compatible with ``no_std`` crates due to the lack of proper ``std`` support for the Wii. Since ``bevy`` is a game engine, you would probably have to write a graphics layer that would work with the Wii's GX system.
